### ISSUE TITLE
Not compatible with Keepass 2.42.1

### ISSUE THREAD

**Issue by mekineer** [JanisEst/KeePassBrowserImporter#28]
"The following plugin is incompatible with the current KeePass version: %path%\KeePassBrowserImporter.plgx"

**Comment by JanisEst** [comment]
It is compatible but without more infos I can't help you.

**Comment by xilinpin** [comment]
I am seeing this problem as well. The platform is Linux (Debian stretch) using mono and the portable version of KeePass 2.42.1. I had seen similar problems with other plugins and the solution was to install more mono components ;-)
However now I have everything (installed the mono-complete meta package) and KeePassBrowserImporter still gives me this error.

**Comment by JanisEst** [comment]
Have a look at the first sentence in the Installation section in the readme.
https://github.com/JanisEst/KeePassBrowserImporter#installation

**Comment by xilinpin** [comment]
Oops, sorry. I came here through Google.

**Comment by Jebtrix** [comment]
Win7 PRO 64bit / KeePass v2.42.1 / KeePassBrowserImporter v1.0.9

Fresh install to to test out KeePass but I'm getting incompatible error:

[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\Testing\KeePass\Plugins\KeePassBrowserImporter.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
ResX file Type System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in the data at line 120, position 4 cannot be located. Line 122, position 5. cannot be parsed.
System.Windows.Forms
   at System.Resources.ResXResourceReader.ParseXml(XmlTextReader reader)
   at System.Resources.ResXResourceReader.EnsureResData()
   at System.Resources.ResXResourceReader.GetEnumerator()
   at KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void ParseXml(System.Xml.XmlTextReader)


Inner:
Type System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in the data at line 120, position 4 cannot be located. Line 122, position 5.
